-- Fide v2 · 3/5 — End-to-end encrypted documents (payslips, CU).
--
-- Format fide-doc-v1, produced in HR's browser (the server never sees plaintext):
--   ciphertext  = XChaCha20-Poly1305(pdf, key = file_key, nonce, ad = "fide-doc-v1|<document_id>|<member_id>")
--   wrapped_key = crypto_box_seal(file_key, employee X25519 public key)   -- 32 + 48 = 80 bytes
-- The ciphertext goes to Storage at {company_id}/{member_id}/{document_id}.bin.
--
-- Flow: create_payroll_batch() → HR uploads each object → publish_payroll_batch()
-- checks every object exists with the declared size → employees download through
-- the document-url Edge Function (signed URL + `downloaded` event).

create type public.document_kind as enum ('cedolino', 'cu', 'other');
create type public.document_status as enum ('draft', 'published', 'superseded', 'deleted');
create type public.document_event as enum ('published', 'downloaded', 'opened', 'superseded', 'deleted');
create type public.batch_status as enum ('draft', 'published');

create table public.payroll_batches (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies (id) on delete cascade,
  kind public.document_kind not null default 'cedolino',
  period date not null check (extract(day from period) = 1),
  title text not null check (char_length(title) between 1 and 120),
  status public.batch_status not null default 'draft',
  created_by uuid references public.members (id),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (company_id, id)
);

create table public.documents (
  -- Generated by the portal before encryption: it is bound into the AEAD data.
  id uuid primary key,
  company_id uuid not null,
  member_id uuid not null,
  batch_id uuid,
  kind public.document_kind not null,
  title text not null check (char_length(title) between 1 and 120),
  period date,
  device_key_id uuid not null,
  storage_path text not null unique,
  format text not null default 'fide-doc-v1' check (format = 'fide-doc-v1'),
  nonce text not null check (public.b64_len(nonce) = 24),
  ciphertext_sha256 text not null check (ciphertext_sha256 ~ '^[0-9a-f]{64}$'),
  size_bytes integer not null check (size_bytes between 17 and 26214400),
  status public.document_status not null default 'draft',
  supersedes_id uuid references public.documents (id),
  created_by uuid references public.members (id),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  first_opened_at timestamptz,
  foreign key (company_id, member_id) references public.members (company_id, id),
  foreign key (company_id, batch_id) references public.payroll_batches (company_id, id),
  foreign key (member_id, device_key_id) references public.device_keys (member_id, id),
  check (storage_path = company_id::text || '/' || member_id::text || '/' || id::text || '.bin')
);

create index documents_member on public.documents (member_id, created_at desc);
create index documents_batch on public.documents (batch_id);

create table public.document_key_wraps (
  document_id uuid not null references public.documents (id) on delete cascade,
  device_key_id uuid not null references public.device_keys (id),
  wrapped_key text not null check (public.b64_len(wrapped_key) = 80),
  created_at timestamptz not null default now(),
  primary key (document_id, device_key_id)
);

-- Proof of delivery (L. 4/1953 electronic payslip delivery): append-only.
create table public.document_access_events (
  id bigint generated always as identity primary key,
  company_id uuid not null,
  document_id uuid not null references public.documents (id),
  member_id uuid not null,
  actor_member_id uuid references public.members (id),
  event public.document_event not null,
  created_at timestamptz not null default now(),
  foreign key (company_id, member_id) references public.members (company_id, id)
);

create index document_access_events_document on public.document_access_events (document_id, created_at);
create index document_access_events_company on public.document_access_events (company_id, created_at desc);

create trigger document_access_events_append_only before update or delete on public.document_access_events
  for each row execute function private.forbid_mutation();

-- ---------------------------------------------------------------------------
-- Storage: ciphertext only, upload-once, no client reads
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('encrypted-documents', 'encrypted-documents', false, 26214400, array['application/octet-stream'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- HR may upload exactly the objects announced by a draft document row of their
-- company. No SELECT/UPDATE/DELETE policies: objects cannot be listed,
-- overwritten or removed by clients, and downloads go through signed URLs.
create policy encrypted_documents_hr_upload on storage.objects for insert to authenticated
  with check (
    bucket_id = 'encrypted-documents'
    and exists (
      select 1 from public.documents d
      where d.storage_path = name
        and d.status = 'draft'
        and d.company_id in (select private.my_hr_company_ids())
    )
  );

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------

-- p_items: [{document_id, member_id, device_key_id, nonce, ciphertext_sha256,
--            size_bytes, wrapped_key, title?, supersedes_id?}]
create function public.create_payroll_batch(
  p_company_id uuid,
  p_kind public.document_kind,
  p_period date,
  p_title text,
  p_items jsonb
)
returns uuid
language plpgsql security definer
set search_path = ''
as $$
declare
  me public.members := private.require_member(p_company_id, '{hr_admin,company_owner}');
  v_batch uuid;
  item jsonb;
  v_doc uuid;
  v_member uuid;
  v_key uuid;
  v_supersedes uuid;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) not between 1 and 2000 then
    raise exception 'invalid_items' using errcode = '22023';
  end if;

  insert into public.payroll_batches (company_id, kind, period, title, created_by)
  values (p_company_id, p_kind, date_trunc('month', p_period)::date, trim(p_title), me.id)
  returning id into v_batch;

  for item in select * from jsonb_array_elements(p_items) loop
    v_doc := (item ->> 'document_id')::uuid;
    v_member := (item ->> 'member_id')::uuid;
    v_key := (item ->> 'device_key_id')::uuid;
    v_supersedes := (item ->> 'supersedes_id')::uuid;

    if not exists (
      select 1 from public.device_keys k
      join public.members m on m.id = k.member_id
      where k.id = v_key and k.member_id = v_member and k.company_id = p_company_id
        and k.status = 'active' and m.status = 'active'
    ) then
      raise exception 'device_key_not_active' using errcode = 'P0001', detail = v_member::text;
    end if;

    if v_supersedes is not null and not exists (
      select 1 from public.documents
      where id = v_supersedes and member_id = v_member and company_id = p_company_id
        and status = 'published'
    ) then
      raise exception 'supersedes_invalid' using errcode = 'P0001', detail = v_supersedes::text;
    end if;

    insert into public.documents (
      id, company_id, member_id, batch_id, kind, title, period, device_key_id, storage_path,
      nonce, ciphertext_sha256, size_bytes, supersedes_id, created_by)
    values (
      v_doc, p_company_id, v_member, v_batch, p_kind,
      coalesce(nullif(trim(item ->> 'title'), ''), trim(p_title)),
      date_trunc('month', p_period)::date, v_key,
      p_company_id::text || '/' || v_member::text || '/' || v_doc::text || '.bin',
      item ->> 'nonce', item ->> 'ciphertext_sha256', (item ->> 'size_bytes')::int,
      v_supersedes, me.id);

    insert into public.document_key_wraps (document_id, device_key_id, wrapped_key)
    values (v_doc, v_key, item ->> 'wrapped_key');
  end loop;

  return v_batch;
end;
$$;

create function public.publish_payroll_batch(p_batch_id uuid)
returns integer
language plpgsql security definer
set search_path = ''
as $$
declare
  b public.payroll_batches;
  me public.members;
  v_missing int;
  v_count int;
begin
  select * into b from public.payroll_batches where id = p_batch_id for update;
  if not found then
    raise exception 'not_found' using errcode = 'P0002';
  end if;
  me := private.require_member(b.company_id, '{hr_admin,company_owner}');
  if b.status <> 'draft' then
    raise exception 'not_draft' using errcode = 'P0001';
  end if;

  select count(*) into v_missing
  from public.documents d
  where d.batch_id = b.id
    and not exists (
      select 1 from storage.objects o
      where o.bucket_id = 'encrypted-documents'
        and o.name = d.storage_path
        and (o.metadata ->> 'size')::bigint = d.size_bytes
    );
  if v_missing > 0 then
    raise exception 'upload_incomplete' using errcode = 'P0001', detail = v_missing::text;
  end if;

  update public.documents set status = 'superseded'
  where id in (select supersedes_id from public.documents where batch_id = b.id and supersedes_id is not null)
    and status = 'published';

  insert into public.document_access_events (company_id, document_id, member_id, actor_member_id, event)
  select d.company_id, d.supersedes_id, d.member_id, me.id, 'superseded'
  from public.documents d
  where d.batch_id = b.id and d.supersedes_id is not null;

  update public.documents set status = 'published', published_at = now()
  where batch_id = b.id;
  get diagnostics v_count = row_count;

  insert into public.document_access_events (company_id, document_id, member_id, actor_member_id, event)
  select d.company_id, d.id, d.member_id, me.id, 'published'
  from public.documents d
  where d.batch_id = b.id;

  update public.payroll_batches set status = 'published', published_at = now() where id = b.id;

  return v_count;
end;
$$;

create function public.mark_document_opened(p_document_id uuid)
returns void
language plpgsql security definer
set search_path = ''
as $$
declare
  d public.documents;
begin
  update public.documents set first_opened_at = coalesce(first_opened_at, now())
  where id = p_document_id
    and member_id in (select private.my_member_ids())
    and status in ('published', 'superseded')
  returning * into d;
  if not found then
    raise exception 'not_found' using errcode = 'P0002';
  end if;

  insert into public.document_access_events (company_id, document_id, member_id, actor_member_id, event)
  values (d.company_id, d.id, d.member_id, d.member_id, 'opened');
end;
$$;

-- service_role (document-url): authorise a download for the signed-in user and
-- log it. Returns what the app needs to decrypt.
create function public.svc_document_download(p_document_id uuid, p_auth_user_id uuid)
returns jsonb
language plpgsql security definer
set search_path = ''
as $$
declare
  d public.documents;
  v_wrap text;
begin
  select doc.* into d
  from public.documents doc
  join public.members m on m.id = doc.member_id
  where doc.id = p_document_id
    and doc.status in ('published', 'superseded')
    and m.auth_user_id = p_auth_user_id
    and m.status = 'active';
  if not found then
    raise exception 'not_found' using errcode = 'P0002';
  end if;

  select wrapped_key into v_wrap from public.document_key_wraps
  where document_id = d.id and device_key_id = d.device_key_id;

  insert into public.document_access_events (company_id, document_id, member_id, actor_member_id, event)
  values (d.company_id, d.id, d.member_id, d.member_id, 'downloaded');

  return jsonb_build_object(
    'document_id', d.id, 'member_id', d.member_id, 'storage_path', d.storage_path,
    'format', d.format, 'nonce', d.nonce, 'wrapped_key', v_wrap,
    'device_key_id', d.device_key_id, 'ciphertext_sha256', d.ciphertext_sha256,
    'size_bytes', d.size_bytes);
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS and grants
-- ---------------------------------------------------------------------------

alter table public.payroll_batches enable row level security;
alter table public.documents enable row level security;
alter table public.document_key_wraps enable row level security;
alter table public.document_access_events enable row level security;

create policy payroll_batches_select on public.payroll_batches for select to authenticated
  using (company_id in (select private.my_hr_company_ids()));

create policy documents_select on public.documents for select to authenticated
  using (
    (member_id in (select private.my_member_ids()) and status in ('published', 'superseded'))
    or company_id in (select private.my_hr_company_ids())
  );

create policy document_key_wraps_select on public.document_key_wraps for select to authenticated
  using (
    exists (
      select 1 from public.documents d
      where d.id = document_id
        and d.member_id in (select private.my_member_ids())
        and d.status in ('published', 'superseded')
    )
  );

create policy document_access_events_select on public.document_access_events for select to authenticated
  using (
    member_id in (select private.my_member_ids())
    or company_id in (select private.my_hr_company_ids())
  );

revoke all on public.payroll_batches, public.documents, public.document_key_wraps,
  public.document_access_events from anon, authenticated;
grant select on public.payroll_batches, public.documents, public.document_key_wraps,
  public.document_access_events to authenticated;
